# Permalinks
permalink: pretty

# Setup
title: Stephen Parish
url: http://stephen.parish.co/

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: :compressed

# About/contact
author:
  name: Stephen Parish
  url: http://stephen.parish.co/
  email: stephen@parish.co
