# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Stephen Parish
tagline:          'A Jekyll theme'
description:      'I make stuff for mobile and web.'
url:              http://localhost:4000

author:
  name:           'Stephen Parish'
  url:            https://twitter.com/stephenparish

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/hyde